# Generated by Django 5.2.8 on 2025-11-16 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sentemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('enroll_course', 'Đăng ký khóa học'), ('complete_lesson', 'Hoàn thành bài học'), ('submit_exam', 'Nộp bài thi thử'), ('view_page', 'Xem trang')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử hoạt động',
                'verbose_name_plural': 'Lịch sử hoạt động',
                'ordering': ['-timestamp'],
            },
        ),
    ]
