# Generated by Django 5.2.8 on 2025-11-16 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'UserActivityHistory', 'verbose_name_plural': 'UserActivityHistory'},
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google')], help_text='Nhà cung cấp Social Auth (ví dụ: google).', max_length=50)),
                ('uid', models.CharField(help_text='ID duy nhất từ nhà cung cấp xã hội.', max_length=255, unique=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='Người dùng nội bộ đã liên kết.', on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Connection',
                'verbose_name_plural': 'Social Connections',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
